2024-09-27 00:52:14.466 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-09-27 00:52:14.467 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration localtuya which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-09-27 00:52:14.467 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration portainer which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-09-27 00:52:14.468 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration dwains_dashboard which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-09-27 00:52:14.468 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration xiaomi_miot which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-09-27 00:52:14.468 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration auto_areas which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-09-27 00:52:14.469 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration spook which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-09-27 00:52:14.469 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration powercalc which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-09-27 00:52:14.469 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration ui_lovelace_minimalist which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-09-27 00:52:14.470 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration sonoff which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-09-27 00:52:14.470 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration pyscript which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-09-27 00:52:16.209 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'dwains_dashboard' calls hass.http.register_static_path which is deprecated because it does blocking I/O in the event loop, instead call `await hass.http.async_register_static_paths([StaticPathConfig("/dwains_dashboard/js", "/config/custom_components/dwains_dashboard/js", True)])`; This function will be removed in 2025.7 at custom_components/dwains_dashboard/load_plugins.py, line 13: hass.http.register_static_path("/dwains_dashboard/js", hass.config.path(f"custom_components/{name}/js"), True), please create a bug report at https://github.com/dwainscheeren/dwains-lovelace-dashboard/issues
2024-09-27 00:52:16.215 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'dwains_dashboard' accesses hass.components.websocket_api. This is deprecated and will stop working in Home Assistant 2024.9, it should be updated to import functions used from websocket_api directly at custom_components/dwains_dashboard/notifications.py, line 220: hass.components.websocket_api.async_register_command(websocket_get_notifications), please create a bug report at https://github.com/dwainscheeren/dwains-lovelace-dashboard/issues
2024-09-27 00:52:16.222 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'dwains_dashboard' calls `async_add_job`, which is deprecated and will be removed in Home Assistant 2025.4; Please review https://developers.home-assistant.io/blog/2024/03/13/deprecate_add_run_job for replacement options at custom_components/dwains_dashboard/__init__.py, line 1590: hass.async_add_job(, please create a bug report at https://github.com/dwainscheeren/dwains-lovelace-dashboard/issues
2024-09-27 00:52:16.229 WARNING (MainThread) [homeassistant.helpers.frame] Detected code that calls async_forward_entry_setup for integration, dwains_dashboard with title:  and entry_id: 01J8GV1YJ2PKAASEDMXY23MR33, which is deprecated and will stop working in Home Assistant 2025.6, await async_forward_entry_setups instead. Please report this issue.
Stack (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module>
    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 189, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once
    handle._run()
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2161, in async_forward_entry_setup
    report(
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 151, in report
    _LOGGER.warning(msg, stack_info=True)
2024-09-27 00:52:32.103 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to open with args ('/config/dwains-dashboard/configs/settings.yaml',) inside the event loop by custom integration 'dwains_dashboard' at custom_components/dwains_dashboard/__init__.py, line 118: with open(hass.config.path("dwains-dashboard/configs/settings.yaml")) as f: (offender: /config/custom_components/dwains_dashboard/__init__.py, line 118: with open(hass.config.path("dwains-dashboard/configs/settings.yaml")) as f:), please create a bug report at https://github.com/dwainscheeren/dwains-lovelace-dashboard/issues
For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#open
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module>
    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 189, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once
    handle._run()
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 462, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_app.py", line 537, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_middlewares.py", line 114, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 83, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 26, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 85, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 242, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 32, in headers_middleware
    response = await handler(request)
  File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 73, in handle
    result = await handler(request, **request.match_info)
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/http.py", line 55, in get
    return await WebSocketHandler(request.app[KEY_HASS], request).async_handle()
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/http.py", line 341, in async_handle
    await self._async_websocket_command_phase(connection, send_bytes_text)
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/http.py", line 492, in _async_websocket_command_phase
    async_handle_str(command_msg_data)
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/connection.py", line 227, in async_handle
    handler(self.hass, self, msg)
  File "/config/custom_components/dwains_dashboard/__init__.py", line 118, in websocket_get_configuration
    with open(hass.config.path("dwains-dashboard/configs/settings.yaml")) as f:

2024-09-27 04:17:33.913 ERROR (Thread-4) [pychromecast.socket_client] [shots's Chromecast(192.168.8.66):8009] Error reading from socket.
2024-09-27 04:17:33.913 WARNING (Thread-4) [pychromecast.socket_client] [shots's Chromecast(192.168.8.66):8009] Error communicating with socket, resetting connection
2024-09-27 04:17:33.921 ERROR (Thread-4) [pychromecast.socket_client] [shots's Chromecast(192.168.8.66):8009] Failed to connect to service HostServiceInfo(host='192.168.8.66', port=8009), retrying in 5.0s
2024-09-27 06:03:06.560 WARNING (MainThread) [homeassistant.components.websocket_api.http.connection] [547545007152] from 192.168.8.124 (Home Assistant/2024.6.1-12936 (Android 12; Quest)): Disconnected: Did not receive auth message within 10 seconds
2024-09-27 06:18:09.694 WARNING (MainThread) [homeassistant.components.websocket_api.http.connection] [547443408416] from 192.168.8.124 (Home Assistant/2024.6.1-12936 (Android 12; Quest)): Disconnected: Did not receive auth message within 10 seconds
2024-09-27 06:33:39.735 WARNING (MainThread) [homeassistant.components.websocket_api.http.connection] [547359699968] from 192.168.8.124 (Home Assistant/2024.6.1-12936 (Android 12; Quest)): Disconnected: Did not receive auth message within 10 seconds
2024-09-27 06:49:09.764 WARNING (MainThread) [homeassistant.components.websocket_api.http.connection] [547407803968] from 192.168.8.124 (Home Assistant/2024.6.1-12936 (Android 12; Quest)): Disconnected: Did not receive auth message within 10 seconds
2024-09-27 06:50:51.303 ERROR (MainThread) [homeassistant.components.hassio] Failed to to call /addons/core_git_pull/stats - Container addon_core_git_pull is not running
2024-09-27 06:52:08.259 ERROR (SyncWorker_2) [custom_components.dwains_dashboard.process_yaml] expected a single document in the stream
  in "/config/configuration.yaml", line 2, column 1
but found another document
  in "/config/configuration.yaml", line 12, column 1
2024-09-27 06:54:15.586 ERROR (MainThread) [homeassistant.components.config] The map integration does not support any configuration parameters, got ['all_addon_configs:rw', 'backup:rw', 'homeassistant_config:rw', 'media:rw', 'share:rw', 'ssl:rw']. Please remove the configuration parameters from your configuration.
2024-09-27 06:54:23.093 ERROR (MainThread) [homeassistant.components.config] The map integration does not support any configuration parameters, got ['all_addon_configs:rw', 'backup:rw', 'homeassistant_config:rw', 'media:rw', 'share:rw', 'ssl:rw']. Please remove the configuration parameters from your configuration.
2024-09-27 06:55:21.931 ERROR (MainThread) [homeassistant.components.config] The map integration does not support any configuration parameters, got ['all_addon_configs:rw', 'backup:rw', 'homeassistant_config:rw', 'media:rw', 'share:rw', 'ssl:rw']. Please remove the configuration parameters from your configuration.
